### ISSUE TITLE
About Dataset:DGraph

### ISSUE THREAD

**Issue by wakeupll** [mala-lab/GGAD#2]
According to your README, I downloaded the dgraphfin dataset from the DGraph official website, but I didn't find the dataset named dgraphfin_adj_list, may I ask you what part of this file is generated?

**Comment by fengduqianhe** [comment]
Hi wakeupll,  sorry for the confusion caused by the oversight, the  dgraphfin_adj_list is generated from the _sparse_to_adjlist()_ in the until.py where it transfers the sparse matrix to adj_list.   I will also upload the generated adj_list file  in the google drive.  Please  refer to the updated google drive.
Thank u for following the work !

**Comment by wakeupll** [comment]
Thank you for your  response.

**Comment by fengduqianhe** [comment]
Hi wakeup, I found the VPN to the school's server doesn't work， I will upload the file as soon as I get back to school on 26th June
